apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: nimage
type: Opaque
data:
  # As credenciais devem ser codificadas em base64
  # Para gerar: echo -n "sua_access_key" | base64
  aws-access-key-id: c3VhX2FjY2Vzc19rZXkK  # "sua_access_key" em base64
  aws-secret-access-key: c3VhX3NlY3JldF9rZXkK  # "sua_secret_key" em base64 