apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: nimage
type: Opaque
data:
  # A senha deve ser codificada em base64
  # Para gerar: echo -n "sua_senha" | base64
  mongodb-root-password: c3VhX3NlbmhhX2RvX21vbmdvZGIK  # "sua_senha_do_mongodb" em base64 