apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: nimage
spec:
  schedule: "0 0 * * *"  # Executa todo dia à meia-noite
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              mongodump --uri="mongodb://root:$(MONGODB_ROOT_PASSWORD)@mongodb:27017/nimage?authSource=admin" --out=/backup
              tar -czf /backup/backup-$(date +%Y%m%d).tar.gz /backup/nimage
              aws s3 cp /backup/backup-$(date +%Y%m%d).tar.gz s3://nimage-backups/
            env:
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            emptyDir: {}
          restartPolicy: OnFailure 